src/pe/gob/mc/cnp/model/domain/Ficha.java
 	package pe.gob.mc.cnp.model.domain;

import java.io.Serializable;
import java.util.Date;


public class Ficha extends Expediente implements Serializable {
	

	private static final long serialVersionUID = 1L;
	
	
	private Integer  codigoFicha;
	private Integer  cantidadAutorizada;
	private Date  fechaExpedicion;
	//private Date  fechaSolicitud;
	private Integer numeroCertificado;
    private String observacion; 
	private String usuarioRegistrador;
	private Integer codigoUsuarioRegistrador;
	private Integer codigoUsuarioAdministrativo;
	private String usuarioEvaluador;
	private Integer codigoUsuarioEvaluador;
	private String usuarioDirector;
	private Integer codigoUsuarioDirector;
	private String estadoFicha;
	private Date  fechaEvaluacion;
	private Date  fechaAprobacion;
	private Date  fechaAsignacionRegistrador;
	private String numeroFichaTexto;	
	private String  tipoPersona;
	private String  nacionalidad;
	private String descripcionInicial;
	private String descripcionFinal;
	private Integer codigoPerfil;
	private String vigente;

	
	public String getVigente() {
		return vigente;
	}

	public void setVigente(String vigente) {
		this.vigente = vigente;
	}

	public Integer getCodigoPerfil() {
		return codigoPerfil;
	}

	public void setCodigoPerfil(Integer codigoPerfil) {
		this.codigoPerfil = codigoPerfil;
	}

	/**
	 * General
	 */
	public Ficha() {
		super();
	}
	
	/**
	 * Nuevo
	 */
	public Ficha(Integer cantidadAutorizada,/* Date fechaSolicitud, */String observacion, Integer codigoUsuarioRegistrador,  String usuarioRegistrador, String tipoPersona  , String nacionalidad , Integer codigoUsuarioAdministrativo) {
		super();	
		this.cantidadAutorizada     = cantidadAutorizada;
		//this.fechaSolicitud         = fechaSolicitud;
		this.observacion         = observacion;
		this.codigoUsuarioRegistrador         = codigoUsuarioRegistrador;
		this.usuarioRegistrador         = usuarioRegistrador;
		this.tipoPersona         = tipoPersona;
		this.nacionalidad         = nacionalidad;
		this.codigoUsuarioAdministrativo         = codigoUsuarioAdministrativo; 
	}
	
	
	/**
	 * Modificación
	 */
	public Ficha(Integer codigoFicha,Integer cantidadAutorizada, /*Date fechaSolicitud,*/ String observacion, Integer codigoUsuarioRegistrador,  String usuarioRegistrador , String tipoPersona  , String nacionalidad ) {
		super();	
		this.codigoFicha         = codigoFicha;
		this.cantidadAutorizada     = cantidadAutorizada;
		//this.fechaSolicitud         = fechaSolicitud;
		this.observacion         = observacion;
		this.codigoUsuarioRegistrador         = codigoUsuarioRegistrador;
		this.usuarioRegistrador         = usuarioRegistrador;	
		this.tipoPersona         = tipoPersona;
		this.nacionalidad         = nacionalidad;

		
	}
	/**
	 * Modificación Observar
	 */
	public Ficha(Integer codigoFicha) {
		super();	
		this.codigoFicha         = codigoFicha;
	
	}

	/**
	 * Modificación Asignación
	 */
	public Ficha(Integer codigoFicha, Integer codigoUsuarioRegistrador,  String usuarioRegistrador ) {
		super();	
		this.codigoFicha         = codigoFicha;
		this.codigoUsuarioRegistrador         = codigoUsuarioRegistrador;
		this.usuarioRegistrador         = usuarioRegistrador;
	//	this.fechaAsignacionRegistrador         = fechaAsignacionRegistrador;
		
	}

	
	
	
	public String getDescripcionInicial() {
		return descripcionInicial;
	}

	public void setDescripcionInicial(String descripcionInicial) {
		this.descripcionInicial = descripcionInicial;
	}

	public String getDescripcionFinal() {
		return descripcionFinal;
	}

	public void setDescripcionFinal(String descripcionFinal) {
		this.descripcionFinal = descripcionFinal;
	}

	public Integer getCodigoUsuarioAdministrativo() {
		return codigoUsuarioAdministrativo;
	}

	public void setCodigoUsuarioAdministrativo(Integer codigoUsuarioAdministrativo) {
		this.codigoUsuarioAdministrativo = codigoUsuarioAdministrativo;
	}

	public Date getFechaAsignacionRegistrador() {
		return fechaAsignacionRegistrador;
	}

	public void setFechaAsignacionRegistrador(Date fechaAsignacionRegistrador) {
		this.fechaAsignacionRegistrador = fechaAsignacionRegistrador;
	}

	public String getNacionalidad() {
		return nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getTipoPersona() {
		return tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public Date getFechaEvaluacion() {
		return fechaEvaluacion;
	}

	public void setFechaEvaluacion(Date fechaEvaluacion) {
		this.fechaEvaluacion = fechaEvaluacion;
	}

	public Date getFechaAprobacion() {
		return fechaAprobacion;
	}

	public void setFechaAprobacion(Date fechaAprobacion) {
		this.fechaAprobacion = fechaAprobacion;
	}

	public Integer getCodigoFicha() {
		return codigoFicha;
	}
	public void setCodigoFicha(Integer codigoFicha) {
		this.codigoFicha = codigoFicha;
	}
	public Integer getCantidadAutorizada() {
		return cantidadAutorizada;
	}
	public void setCantidadAutorizada(Integer cantidadAutorizada) {
		this.cantidadAutorizada = cantidadAutorizada;
	}
	public Date getFechaExpedicion() {
		return fechaExpedicion;
	}
	public void setFechaExpedicion(Date fechaExpedicion) {
		this.fechaExpedicion = fechaExpedicion;
	}
	/*public Date getFechaSolicitud() {
		return fechaSolicitud;
	}
	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}*/
	public Integer getNumeroCertificado() {
		return numeroCertificado;
	}
	public void setNumeroCertificado(Integer numeroCertificado) {
		this.numeroCertificado = numeroCertificado;
	}
	public String getObservacion() {
		return observacion;
	}
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	public String getUsuarioRegistrador() {
		return usuarioRegistrador;
	}
	public void setUsuarioRegistrador(String usuarioRegistrador) {
		this.usuarioRegistrador = usuarioRegistrador;
	}
	public Integer getCodigoUsuarioRegistrador() {
		return codigoUsuarioRegistrador;
	}
	public void setCodigoUsuarioRegistrador(Integer codigoUsuarioRegistrador) {
		this.codigoUsuarioRegistrador = codigoUsuarioRegistrador;
	}
	public String getUsuarioEvaluador() {
		return usuarioEvaluador;
	}
	public void setUsuarioEvaluador(String usuarioEvaluador) {
		this.usuarioEvaluador = usuarioEvaluador;
	}
	public Integer getCodigoUsuarioEvaluador() {
		return codigoUsuarioEvaluador;
	}
	public void setCodigoUsuarioEvaluador(Integer codigoUsuarioEvaluador) {
		this.codigoUsuarioEvaluador = codigoUsuarioEvaluador;
	}
	public String getUsuarioDirector() {
		return usuarioDirector;
	}
	public void setUsuarioDirector(String usuarioDirector) {
		this.usuarioDirector = usuarioDirector;
	}
	public Integer getCodigoUsuarioDirector() {
		return codigoUsuarioDirector;
	}
	public void setCodigoUsuarioDirector(Integer codigoUsuarioDirector) {
		this.codigoUsuarioDirector = codigoUsuarioDirector;
	}
	public String getEstadoFicha() {
		return estadoFicha;
	}
	public void setEstadoFicha(String estadoFicha) {
		this.estadoFicha = estadoFicha;
	}	
	public String getNumeroCertificadoFormato() {
		  String d = "";
	      if(this.numeroCertificado!=null){
	    	  d = String.format("%06d", this.numeroCertificado);
		  }
		  return d;
		}	
	
	
	public String getDescripcionEstadoFicha() {
		String d = "";
		
		if(this.estadoFicha!=null){		
			switch((char)(this.estadoFicha).charAt(0)) {
				case 'C':
					d = "Nuevo";
					break;
				case 'T':
					d = "Asignado a Técnico";				
					break;
				case 'E':
					d = "Enviado a Supervisor";				
					break;
				case 'S':
					d = "Enviado a Director";				
					break;
				case 'O':
					d = "Observado";				
					break;
				case 'A':
					d = "Aprobado";				
					break;					
				case 'D':
					d = "Denegado";				
					break;
				case 'B':
					d = "Abandono";				
					break;
			}		
		}
		
		return d;
	}
		
	
	private String motivoNoAtencion;
	
	private Date fechaNoAtencion;
	
	
	
	public Date getFechaNoAtencion() {
		return fechaNoAtencion;
	}

	public void setFechaNoAtencion(Date fechaNoAtencion) {
		this.fechaNoAtencion = fechaNoAtencion;
	}

	public String getMotivoNoAtencion() {
		return motivoNoAtencion;
	}

	public void setMotivoNoAtencion(String motivoNoAtencion) {
		this.motivoNoAtencion = motivoNoAtencion;
	}

	public String getDescripcionNoAtencion() {
		String d = "";
		
		if(this.motivoNoAtencion!=null){		
			switch((char)(this.motivoNoAtencion).charAt(0)) {
				case 'A':
					d = "Abandono del trámite";
					break;
				case 'D':
					d = "Denegación de todos los bienes solicitados para exportación";				
					break;				
			}		
		}
		
		return d;
	}
	
	
	private String nombreArchivo;
	private String rutaArchivo;	
    private String rutaCertificadoDocumento;

    private String rutaCertificadoDocumentoFirma;
	// 16-10-2019
	private String nombreArchivo_firma;
	private String rutaArchivo_firma;
	private String codcert;
	
	public String getCodcert() {
		return codcert;
	}

	public void setCodcert(String codcert) {
		this.codcert = codcert;
	}

	public String getNombreArchivo() {
		return nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	public String getRutaArchivo() {
		return rutaArchivo;
	}

	public void setRutaArchivo(String rutaArchivo) {
		this.rutaArchivo = rutaArchivo;
	}

	public String getRutaCertificadoDocumento() {
		String ruta="";
		
		if(nombreArchivo!=null){
			
			ruta= rutaArchivo+nombreArchivo;
			
		}
		
		return ruta;
	}


	public String getRutaCertificadoDocumentoFirma() {
		String ruta="";
		
		if(nombreArchivo_firma!=null){
			
			ruta= rutaArchivo_firma+nombreArchivo_firma;
			
		}
		
		return ruta;
	}
	
	
	public String getNombreArchivo_firma() {
		return nombreArchivo_firma;
	}

	public void setNombreArchivo_firma(String nombreArchivo_firma) {
		this.nombreArchivo_firma = nombreArchivo_firma;
	}

	public String getRutaArchivo_firma() {

WebContent/pages/registro/bandejaConsultaCertificados.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

<ui:composition 
xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
     xmlns:f="http://java.sun.com/jsf/core"
     xmlns:ui="http://java.sun.com/jsf/facelets"
     xmlns:a4j="http://richfaces.org/a4j"
     xmlns:rich="http://richfaces.org/rich"> 

<style>
.alignCenter
{
text-align:center;
}
</style>
	
<div class="titSeccion">
	 <div class="iconoSeccion">MINC-CNP | BANDEJA DE CONSULTA DE CERTIFICADO</div>        
</div>	

  <f:subview id="svfrmExpBandejaBandAUX">
  	<a4j:form id="parametrosBandAUX"   >
   <div class="contenidoBtnesSup">
    <h:panelGroup id="camposIngresoBandAUX" >  
     <table border="0" width="100%">
       <tr>   <td width="5%" > </td>
                <td width="85%" > </td>
                <td width="10%"></td>
      </tr>
        <!--  -->  
           <tr><td> </td>
                <td >    
                <table width="100%"> 
                <tr>
                <td width="20%"></td>
                <td width="15%"></td>
                <td  width="3%"></td>
                <td  width="31%"></td>
                <td  width="31%"></td>
                </tr>
                
                      <tr>
				<td  colspan="5">
				<table width="100%">
				<tr>
					
				  <td align="left" width="14%"><h:outputText id="lblNumeroCertBusqAUX" value="N° Certificado:" /></td>
                  <td width="25%">  <h:inputText id="txtNumeroCertBusqAUX" value="#{fichaBean.numeroCertificado}" maxlength="10" style="width:99%"   onkeypress="return soloNumeros(event);" >
                       
                       </h:inputText>
                      	 </td>  
			  	
			  	 <td align="right" width="12%"> </td>
                  <td width="12%" >  
					</td> 

					<td width="20%" align="right"><h:outputText id="lblUsuarioRegistroAUX" value="N° Expediente:" rendered="#{usuarioBean.sesCodigoPerfil != usuarioBean.ctePerfilRegistrador}"  /></td>
					
					<td  width="17%" >
					<h:outputText id="lblFormatoNumeroExpedienteCONSLAUX" value="(Formato:######-AÑO)" style="font-size:10px"/><br></br>
					 <h:inputText id="txtNroExpedienteAUX" value="#{fichaBean.numeroExpediente}" maxlength="15" style="width:90%"  onkeypress="return soloNumerosConGuion(event);"  >
                           <f:converter converterId="ConverterToUpperString"/>
                       </h:inputText></td>
				</tr>
				
				<tr>
				    <td align="left"  ><h:outputText id="lblNombreAdministradoAUX" value="Administrado:" /></td>
                  <td  colspan="5" >  <h:inputText id="txtNombreAdministradoAUX" value="#{fichaBean.nombreAdministrado}" maxlength="80" style="width:99%"   >
                           <f:converter converterId="ConverterToUpperString"/>
                       </h:inputText>
                      	 </td>  
				</tr>
				
				</table>
				</td>
				</tr>                          
               	      
				</table>		      
                </td>
                <td  rowspan="4" valign="top" align="center">
                         
						<a4j:commandLink id="lnkParamMat2AUX" styleClass="btnInteriores" action="#{fichaBean.consultaBandejaCertificados}" reRender="detallesBody" oncomplete="mostrarMsg()" > 
                    		<span class="buscar">Buscar</span>
                     	</a4j:commandLink>
                     	<a4j:commandLink id="lnkParamMat3AUX" styleClass="btnInteriores" action="#{fichaBean.limpiarBandejaConsultaCertificados}" reRender="parametrosBandAUX"> 
                    		<span class="limpiar">Limpiar</span>
           				</a4j:commandLink>
           				
                </td>
                
                </tr>
                
                 
                
                
                 <tr><td> </td>
                <td >    
                <table width="100%"> 
                <tr>
               <td width="20%"></td>
                <td width="30%"></td>
                <td  width="3%"></td>
                <td  width="30%"></td>
                <td  width="17%"></td>
                </tr>                          
                <tr>
                 <td  >			  
		               <h:outputText id="lblFechaExpedicionAUX" value="Fecha de Certificado:" />
			     </td>	
			        
               			  				
									
			   <td >			  
			     <h:outputText id="lblFechaIniCertAUX" value="Fecha de Inicio:"   style="font-size:10px"/>     <br/>  
						     <table  style="margin-left:2px; width:100%;"   ><tr >	<td>
						   <rich:calendar id="txtIngresoIniCertAUX" datePattern="dd/MM/yyyy" value="#{fichaBean.fechaListIni}"  inputSize="10" 
						   showWeeksBar="false"  direction="auto" enableManualInput="false"  ajaxSingle="true"  popup="true" converterMessage="#{msj.form_bandeja_fechaIni_converter}" >     
							<f:convertDateTime pattern="dd/MM/yyyy"/>
							</rich:calendar>	
						    </td></tr> </table>	
			  </td>	
			  <td></td>
			   <td >			  
			     <h:outputText id="lblFechaFinCertAUX" value="Fecha de Fin:" style="font-size:10px"/>     <br/>  
						     <table  style="margin-left:2px; width:100%;"   ><tr >	<td>
						   <rich:calendar id="txtIngresoFinCertAUX" datePattern="dd/MM/yyyy" value="#{fichaBean.fechaListFin}"  inputSize="10" 
						   showWeeksBar="false"  direction="auto" enableManualInput="false"  ajaxSingle="true"  popup="true" converterMessage="#{msj.form_bandeja_fechaFin_converter}" >     
							<f:convertDateTime pattern="dd/MM/yyyy"/>
							</rich:calendar>	
						    </td></tr> </table>	
			  </td>	
			  
				</tr>		      
				</table>		      
                </td>
               
                
                </tr>   
     </table>   
     </h:panelGroup>
   </div>


<div style="margin: 5px;font-size:large;color:#009">
   <h:panelGroup id="detalleTablaCertificadosAUX" >      
          <rich:dataTable id="DataCertificadosAUX" value="#{fichaBean.listaCertificados}" binding="#{fichaBean.tablaCertificados}"   var="ma" style="margin:auto;width:800px;margin-top:20px"  rows="10"
                                onRowMouseOver="this.style.backgroundColor='#def'"
                    			onRowMouseOut="this.style.backgroundColor='#{a4jSkin.tableBackgroundColor}'">
	           
	           <rich:column  width="10px"   id="colNro11AUX" style="text-align:center;">
	              <f:facet name="header">	                
				     	<h:outputText id="lblMatRIn1AUX" value="N°" style="font-weight: bold ; text-align:center;"/>
			
	              </f:facet>
	              <h:outputText id="idndMatRIn11AUX" value="#{ma.item}"/>
	            </rich:column> 	           
	            
	            
	              <rich:column   id="colMatExpedienteAUX"  style="text-align:center;" width="20px"  >
	              <f:facet name="header" styleClass="cabTabla">	
				     <h:outputText id="lblMatExpedienteAUX" value="N° Expediente" style="font-weight:bold"/>
	              </f:facet>
	              <h:outputText id="idwMatExpedienteAUX" value="#{ma.numeroExpediente}" style=" color:#{ma.motivoNoAtencion!=null?'RED':'BLACK'} "/>
	            </rich:column>
	            
	            
	            <rich:column   id="colMatAdministradoAUX"  style="text-align:center;" width="30px"  >
	              <f:facet name="header" styleClass="cabTabla">	
				     <h:outputText id="lblMatAdministradoAUX" value="Administrado" style="font-weight:bold"/>
	              </f:facet>
	              <h:outputText id="idwMatAdministradoAUX" value="#{ma.nombresApellidos}"/>
	            </rich:column>
	           
	             <rich:column   id="colMat2523AUX"  style="text-align:center;" width="20px"  >
	              <f:facet name="header" styleClass="cabTabla">	
	              	<h:panelGrid id="tblArqDiametro1AUX" columns="1"  style="margin: 0 auto;">
	              	<h:outputText id="lblMat25231AUX" value="Cantidad" style="font-weight:bold"/>
	              	<h:outputText id="lblMat25232AUX" value="Autorizada" style="font-weight:bold"/>	              	
	              	</h:panelGrid>
				     
	              </f:facet>
	              <h:outputText id="idwMat2532AUX" value="#{ma.cantidadAutorizada}"/>
	            </rich:column>
	            
	              <rich:column   id="colMat25AUX"  style="text-align:center;" width="20px"  >
	              <f:facet name="header" styleClass="cabTabla">	
				     <h:outputText id="lblMat25AUX" value="N° Certificado" style="font-weight:bold"/>
	              </f:facet>
	              <h:outputText id="idwMat25AUX" value="#{ma.numeroCertificadoFormato}"/>
	            </rich:column>
	             
	             
	             <rich:column  id="colFechaCertAUX" width="20px" style="height:20px;text-align:center;">
	              <f:facet name="header">
	                <h:outputText id="idwFechaCertAUX" value="Fecha Certificado" style="font-weight:bold"/>
	              </f:facet>
	              <h:outputText id="idwMatFechaCertAUX" value="#{ma.fechaExpedicion}">
	              		<f:convertDateTime pattern="dd/MM/yyyy"/>
		         </h:outputText>
	            </rich:column>	
	            
	           
	            
	            <rich:column id="idAccionesMatLBAUX" width="115px" style="height:20px;text-align:center;"  >
	             <f:facet name="header">
	              <h:outputText id="idwMat46AUX" value="Acciones" style="font-weight:bold"/>
	             </f:facet> 
	             
	              <h:commandLink id="imodificarMat2CERTAUX"  action="#{fichaBean.seleccionarCertificado}" reRender="detallesBody"   rendered="#{ma.numeroCertificado !=null and (ma.nombreArchivo!=null and ma.nombreArchivo!= '')  }"   >
	                    <a4j:actionparam name="ruta3" value="/pages/registro/formAdjuntarCertificadoVer.xhtml" assignTo="#{beanLinkMenu.ruta}"/>
	                    <f:param name="soloVerCertificado" value="S"  />	                
	                   <h:graphicImage value="/common/images/find.png"
	                                            style="border:2;width : 20px; height : 20px;"/>   
	              </h:commandLink> 
	               
	              <rich:toolTip id="tM198CERTAUX" for="imodificarMat2CERTAUX" direction="top-left" value="Ver Formulario" />
	              
	                <rich:spacer  id="idEspacioMat1CERTAUX"  width="10" height="10" ></rich:spacer>
	             
	                <h:outputLink id="colbtnVerAccionAdjuntoCERTificadoAUX" value="#{ma.rutaCertificadoDocumento}"
				    		 					target="_blank" rendered="#{(ma.nombreArchivo!=null and ma.nombreArchivo!= '')}">
				    		 					<h:graphicImage value="/common/images/iconos/pdf.png" /></h:outputLink>
				    		 					
	               <rich:toolTip id="tM198ABCCERTAUX" for="colbtnVerAccionAdjuntoCERTificadoAUX" direction="top-left" value="Ver Archivo" />	             
	              
	              
	               
	            </rich:column>
	            
		      
		     <f:facet name="footer">

		      	<h:panelGrid columns="5" columnClasses="alignCenter"  fastControls="hide" id="paginacion172AUX">
		      	<h:outputText id="lblCantidadBSAUX" value="Cantidad:" style="font-weight:bold; font-size:12px;"/>
	   		       <h:outputText id="cantElemenBSAUX"  value="#{fichaBean.cantidadElementosPaginado}"  style="font-weight:bold; font-size:12px;"/>
	   		       <rich:spacer  id="idw182AUX"  width="60" height="10" ></rich:spacer>
	   			 <h:outputText  id="idw183AUX"  value="Página " />
		     	 <rich:datascroller  id="idw184AUX"  for="DataCertificadosAUX" maxPages="5"   fastControls="hide"  >
		     	 	<f:facet name="previous">
                        <h:outputText  id="idw186AUX"  value="Anterior" styleClass="scrollerCell" />
                    </f:facet>
                    <f:facet name="previous_disabled">
                        <h:outputText  id="idw187AUX"  value="Anterior" styleClass="scrollerCell" />
                    </f:facet>
                    <f:facet name="next">
                        <h:outputText  id="idw188AUX"  value="Siguiente" styleClass="scrollerCell" />
                    </f:facet>
                    <f:facet name="next_disabled">
                        <h:outputText  id="idw189AUX"  value="Siguiente"  styleClass="scrollerCell" />
                    </f:facet>
		     	 </rich:datascroller>
		       </h:panelGrid>

			  </f:facet>
		      
		      
            </rich:dataTable>
      </h:panelGroup>   
</div>

<div class="msgInfo" id="msg">				
					<rich:messages ajaxRendered="true" infoClass="rf-msgs-inf" warnClass="rf-msgs-wrn" errorClass="rf-msgs-err"/>			   	
	    </div> 

 </a4j:form>
 </f:subview>  
   

</ui:composition>

</html>